on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: "Upload Release"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
      
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            release/windows_configurator.exe
