on: [push]

name: Rust-Release-Nightly

jobs:
  build_and_test:
    name: Rust project
    #runs-on: windows-latest
    runs-on: truenas-winservervm
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: "marvinpinto/action-automatic-releases@latest"
      
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            ./target/release/windows_configurator.exe

