on:
  push:
    tags:
      - "v*.*.*"

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/windows_configurator.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
